version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: go_backend_dev
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

volumes:
  db_data:
