# .air.toml - Configuração do Air para hot reload

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "tmp/main"
  full_bin = "./tmp/main"
  watch_dir = "."
  watch_ext = ["go", "tpl", "tmpl", "html"]
  ignore_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  delay = 1000 # ms
  stop_on_error = true
  log = "build-errors.log"
  poll = true
  poll_interval = 500

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
